# Generated by Django 3.1.5 on 2021-02-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filmsapp', '0003_auto_20210125_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Активный'),
        ),
    ]
